  name: createstructure
  version: '0.3'
  summary: Single-line elevator pitch for your amazing snap # 79 char long summary
  description: |
    With this program, you can easily create a repository on GitHub with a basic template, personalized for your use.
    To see more visit: https://github.com/createstructure/createstructure/
    
  grade: stable
  confinement: strict

  parts:
    createstructure:
      plugin: cmake
      source: debian

  apps:
    createstructure:
      command: createstructure