name: Tests on every push

on:
  push

jobs:
  test-pip:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
        pip install -r requirements/requirements.txt
    - name: Build
      run: |
        python setup.py sdist bdist_wheel

  test-deb:
    runs-on: ubuntu-latest

    steps:
    - name: Build Debian package
      uses: dawidd6/action-debian-package@v1
      with:
        source_directory: debian # optional, relative to workspace directory
        artifacts_directory: output # optional, relative to workspace directory
    - run: ls
    