name: Tests on every push

on:
  push

jobs:
  test-pip:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
        pip install -r requirements/requirements.txt
    - name: Build
      run: |
        python setup.py sdist bdist_wheel
    - name: Try a run
      run: |
        python -c "exec(\"from datetime import datetime as dt;from create_structure import create_structure;create_structure(answers={'name':str(int(dt.now().timestamp())),'extention':'py','descr':str(int(dt.now().timestamp())),'prefix':'push-test','team':'','private':'N'})\")" -t=${{ secrets.GITHUB_TOKEN }} -s=[CastellaniDavide] -o=CastellaniDavideTest -i=[.vs,.vscode]
