name: Tests on every push

on:
  push

jobs:
  test-pip:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
        pip install -r requirements/requirements.txt
    - name: Build
      run: |
        python setup.py sdist bdist_wheel

  build-linux-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependences
        run: |
          sudo add-apt-repository ppa:jyrki-pulliainen/dh-virtualenv
          sudo apt-get update
          sudo apt-get install build-essential debhelper devscripts equivs dh-virtualenv python3.8

      - name: Create Debian package
        run: |
          cd debian
          sudo debuild -us -uc

      - name: Create fake inputs
        run: |
          echo "fake-token" > answers
          echo "[fake-source1,fake-source2,fake-sourcen]" >> answers
          echo "fake-organization" >> answers
          echo "[fake-ignore1,fake-ignore2,fake-ignoren]" >> answers

      - name: Install package
        run: sudo dpkg -i ./createstructure_7.0_amd64.deb < answers
