name: Check installation

on:
    push

jobs:
  test-ubuntu-debian:
    runs-on: ubuntu-latest
    steps:
    - name: Installation
      run: |
        sudo apt install git python3 python3-pip python-setuptools
        cd ~
        git clone https://github.com/CastellaniDavide/create_structure.git
        cd create_structure
        git pull --force
        pip3 install setuptools
        pip3 install -r requirements/requirements.txt
        alias create_structure="python3 ~/create_structure/bin/create_structure.py -t=${{ secrets.GITHUB_TOKEN }} -o=CastellaniDavideTest"
    - name: Create test file
      run: |
        echo $(($(date +%s%N)/1000000)) > testfile.txt
        echo default >> testfile.txt
        echo https://github.com/CastellaniDavide/create_structure/blob/master/.github/workflows/test.yml >> testfile.txt
        echo test >> testfile.txt
        echo >> n
        echo >> n
    - name: Test execution
      run: ls # create_structure < testfile.txt

  test-windows:
    runs-on: windows-latest
    steps:
    - name: Installation
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
        choco install git.install -y
        choco install python3 --pre -y
        cd "C:\Program Files"
        git clone https://github.com/CastellaniDavide/create_structure.git
        cd create_structure
        git pull --force
        pip3 install -r requirements/requirements.txt
        New-Item -Path $Profile -Type File -Force
        echo "Function CreateStructureFunction {python 'C:\Program Files/create_structure/bin/create_structure.py' -t=${{ secrets.GITHUB_TOKEN }} -o=CastellaniDavideTest'}" > $Profile
        echo "Set-Alias -Name create_structure -Value CreateStructureFunction" >> $Profile
        python 'C:\Program Files/create_structure/bin/create_structure.py' -t=${{ secrets.GITHUB_TOKEN }} -o=CastellaniDavideTest #create_structure 
