name: Check use

on:
    push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Installation
      run: |
        sudo apt install git python3 python3-pip python-setuptools
        cd ~
        git clone https://github.com/CastellaniDavide/create_structure.git
        cd create_structure
        git pull --force
        pip3 install setuptools
        pip3 install -r requirements/requirements.txt
        alias create_structure="python3 ~/create_structure/bin/create_structure.py -t=${{ secrets.GITHUB_TOKEN }} -o=CastellaniDavideTest"
    
