name: Check installation

on:
    push

jobs:
  test-ubuntu-debian-manual:
    runs-on: ubuntu-latest
    steps:
    - name: Installation & execution
      run: |
        sudo apt install git python3 python3-pip python-setuptools
        cd ~
        git clone https://github.com/CastellaniDavide/create_structure.git
        cd create_structure
        git pull --force
        pip3 install setuptools
        pip3 install -r requirements/requirements.txt
        alias create_structure="python3 ~/create_structure/bin/create_structure.py -t=${{ secrets.REPO_TOKEN }} -o=CastellaniDavideTest"
        
  test-windows-manual:
    runs-on: windows-latest
    steps:
    - name: Installation
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
        choco install git.install -y
        choco install python3 --pre -y
        cd "C:\Program Files"
        git clone https://github.com/CastellaniDavide/create_structure.git
        cd create_structure
        git pull --force
        pip3 install -r requirements/requirements.txt
        New-Item -Path $Profile -Type File -Force
        echo "Function CreateStructureFunction {python 'C:\Program Files/create_structure/bin/create_structure.py' -t=${{ secrets.REPO_TOKEN }} -o=CastellaniDavideTest'}" > $Profile
        echo "Set-Alias -Name create_structure -Value CreateStructureFunction" >> $Profile

  test-install-using-pypi:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [ubuntu-latest, windows-latest]
    
    steps:
    - name:  Install & Test
    run:   |
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt install git python3 python3-pip
          pip install createstructure
          python3 -c "exec(\"from create_structure import create_structure\ncreate_structure()\")"
        elif [ "$RUNNER_OS" == "Windows" ]; then
          Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
          choco install git.install -y
          choco install python3 --pre -y
          pip install createstructure
          python3 -c "exec(\"from create_structure import create_structure\ncreate_structure()\")"
        else
          echo "$RUNNER_OS not supported"
          exit 1
        fi
    shell: bash
